name: deploy

on:
  push:
    branches:
      - master
jobs:
  push-to-gh-page:
    # if: "contains(github.event.head_commit.message, '[deploy]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: use Node.js 14
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14.x'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn run build

      - name: Set SSH Environment
        env:
          DOCS_DEPLOY_KEY: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_TOKEN" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com > ~/.ssh/known_hosts
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
          git config --global user.email "bootx@outlook.com"
          git config --global user.name "bootx"

      - name: Delete gh-pages branch
        run: |
          git push origin --delete gh-pages

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          deploy_key: ${{secrets.DEPLOY_TOKEN}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./.vitepress/dist
          CNAME: doc.bootx.cn
